version: "3.8"
services:
  app:
    image: yoonxjoong/redis-lock-test:latest
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - redis-net

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge
